### ISSUE TITLE
OBJECTID field is always added

### ISSUE THREAD

**Issue by jkerr5** [koopjs/FeatureServer#127]
Even if the `metadata` specifies an `idField`, it looks like the `OBJECTID` field is still added to the list of fields.

I think I have traced it back to here in the code https://github.com/koopjs/FeatureServer/blob/4515bedde61b9e4c6bf68737554f304d04da048c/src/field/index.js#L27

It should be looking for the field that the metadata says is the `idField`

**Comment by jkerr5** [comment]
What if clients pass in a where clause with OBJECTID? The provider would
need to have special logic looking for the OBJECTID column to map it to the
ID column. This seems like a behavior that pass-through providers should be
able to control as it is really changing what columns the client think are
available.

**Comment by rgwozdz** [comment]
Yup, you've identified a flaw that needs to be addressed.  At minimum we need Winnow to be processing `WHERE`s with OBJECTIDs properly when `idField` determines its value.  While addressing this, we might be able to take a deeper dive and see if we can avoid the workaround noted above.

**Comment by rgwozdz** [comment]
@jkerr5 - this is now fixed in FeatureServer 2.16.3 and Winnow 1.16.5.  If you set an `idField` in metadata, that will be used as the `objectIdField` in ArcGIS clients;  a duplicate field named `OBJECTID` is no longer added.  
Thanks again for bring this back to my attention.

**Comment by jkerr5** [comment]
Thanks Rich!
