### ISSUE TITLE
A change was introduced in 2.16.3 the is incompatible with Insights

### ISSUE THREAD

**Issue by jkerr5** [koopjs/FeatureServer#142]
I haven't had a chance to debug the issue yet but testing with 2.16.3 results in a "something went wrong" error from Esri Insights. Reverting back to 2.16.2 makes it work again.

**Comment by rgwozdz** [comment]
@jkerr5 - I'll need a little more info to reproduce; so far I am unable to generate the error you note.  Here are my steps:
1. Serve polygon data with Koop and FeatureServer 2.16.3
2. Add the Koop service to ArcGIS Online as a new item
3. Add the item from (2) to ArcGIS Insights workbook

I am able to add the item successfully to the Insights workbook.  Is this where you had problems?

**Comment by rgwozdz** [comment]
If you would like to send me a CSV, JSON or GeoJSON extract of some of the data that generates the error, I would gladly see if I can reproduce.

**Comment by jkerr5** [comment]
Sorry, on holiday so I haven't had a chance to get back to this. I'll get
you some more info next week.

**Comment by rgwozdz** [comment]
Anything more on this?

**Comment by rgwozdz** [comment]
Going to close this one do to in activity.  Feel free to re-open if there are additional reports of trouble with InSights - I haven't been able to reproduce.
