### ISSUE TITLE
Cannot require featureserver as of (2.21.0)

### ISSUE THREAD

**Issue by dbreen1** [koopjs/FeatureServer#164]
Hi,

It appears the latest npm package (2.21.0) is not working. Error is(Cannot find module 'featureserver'). Looks like it wasn't packaged correctly.

**Comment by rgwozdz** [comment]
Correct, apologies.  Will re-release shortly.

**Comment by rgwozdz** [comment]
Just released 2.21.1 which includes proper packing of the module.

**Comment by dbreen1** [comment]
Perfect, thanks, I can confirm that it works again.
