### ISSUE TITLE
No default renderer for MultiPoint service

### ISSUE THREAD

**Issue by sfabijanski** [koopjs/FeatureServer#165]
When creating a multipoint provider in Koop, the FeatureServer appears to work correctly and returns a json object without error. However, no renderer is included in the _drawingInfo_ object, eg. `"drawingInfo": {
        "labelingInfo": null
    },`
This causes problems downstream when trying to include the service in an AGOL web map. The service will load, but applied symbology will not persist, and the service will not render properly in the map when included in Web Appbuilder.

The expectation would be that a default renderer would be applied as it does with a point service.

As a workaround, I was able to leverage behavior added in #162 . This allows a developer to provide a renderer template in the metadata for the provider. When the renderer is provided in metadata, the mutlipoint service correctly passes the renderer as part of drawingInfo.

**Comment by rgwozdz** [comment]
Added in 3.2.0.
