### ISSUE TITLE
Make returnCountOnly etc. parameters more tolerant in line with ArcGIS Server support

### ISSUE THREAD

**Issue by nheminger** [koopjs/FeatureServer#174]
The parameters returnCountOnly, returnExtentOnly, and returnIdsOnly are currently not tolerant of mixed capitalization which causes errors consuming KoopJS services in the ArcGIS API for Python 1.7.0.

For example. if you specify returnCountOnly=False (note the capitalization on 'F') then KoopJS interprets the presence of this parameter as the requirement to return the count only (when it should NOT). This leads to clients (such as ArcGIS API for Python) having errors as they expect features to be returned when returnCountOnly=False, but simply the count is returned.

NOTE: the [Spec](https://developers.arcgis.com/rest/services-reference/query-feature-service-.htm) for feature service query does specify lowercase capitalization, so the treatment may be correct but I am suggesting it be made more tolerant since ArcGIS Server instances are tolerant in that way.

**Comment by haoliangyu** [comment]
related issue https://github.com/koopjs/koop-core/issues/60
