### ISSUE TITLE
When `returnCountOnly` and `returnExtentOnly` are true, `outSR` is seemingly ignored

### ISSUE THREAD

**Issue by LeviRemi** [koopjs/FeatureServer#215]
Could someone help me understand why `outSR` is not passed into `getExtent()` when `returnCountOnly` and `returnExtentOnly` are set to `true`?
https://github.com/koopjs/FeatureServer/blob/0bee461f0e1afebd96117c31f70708ef3eb2c3dd/lib/query.js#L182-L185

See `getExtent()` here:
https://github.com/koopjs/FeatureServer/blob/0bee461f0e1afebd96117c31f70708ef3eb2c3dd/lib/query.js#L284-L315

This code is the reason I believe I'm getting the wrong extent returned using ArcGIS Online to "zoom to" a Koop-served Feature Layer.

When querying with `returnExtentOnly = true` and `returnCountOnly = false`, I am seeing the accurately projected 102100 extent based on the features in my layer.
![Screen Shot 2022-02-25 at 3 52 52 PM](https://user-images.githubusercontent.com/21701076/155818253-ea326f9a-7891-4e50-932e-b8e1a1c8c0fe.png)

However, when querying with `returnExtentOnly = true` and `returnCountOnly = true` (the default params when using "zoom to" in the ArcGIS Online Map Viewer), I am getting the same projected coordinates but with an incorrectly labeled SR:
![Screen Shot 2022-02-25 at 3 58 57 PM](https://user-images.githubusercontent.com/21701076/155818933-51e4c62a-a543-47ec-9992-7da2c4687c6f.png)

Am I missing some metadata option to make this work correctly? I tried to modify the GeoJSON to include an `extent` object with a hard-defined bbox in the correct SR, but this extent did not show up in the query results.

**Comment by rgwozdz** [comment]
Working on a patch...

**Comment by rgwozdz** [comment]
@LeviRemi - sorry for the delay.  The patch is released (v3.3.2).  Can you confirm it fixes your noted issue?

**Comment by rgwozdz** [comment]
Ok, I've update Koop Geoservices.

**Comment by LeviRemi** [comment]
@rgwozdz The "zoom to" is working great now! Thank you.
