### ISSUE TITLE
Ability to override default server `copyrightText`

### ISSUE THREAD

**Issue by brightgarden** [koopjs/FeatureServer#222]
It would be great if the server `copyrightText` could be overridden to replace the default text "Copyright information varies from provider to provider, for more information please contact the source of this data".

I am willing to make the change and submit a PR!

Thanks for considering this.

**Comment by rgwozdz** [comment]
sure, we can do that.  Thanks @brightgarden.

**Comment by rgwozdz** [comment]
https://github.com/koopjs/FeatureServer/pull/223, merged and published in 3.5.0.
