### ISSUE TITLE
Field editable/nullable flags are not used in layer info

### ISSUE THREAD

**Issue by schmidtk** [koopjs/FeatureServer#247]
When providing layer info, the generated fields use `LayerField` which sets the editable/nullable flags here:
https://github.com/koopjs/FeatureServer/blob/bce9f2cb52d59746dbd6031917490e4e5ffbe112/lib/helpers/fields/layer-fields.js#L13

This always sets the values to the default (false), even if `metadata.fields` provides these values. This is a regression from the field generation refactor.

**Comment by rgwozdz** [comment]
Ok.  Editable should probably always be false given FeatureServer does not provide any create/update capabilities.  But perhaps nullable needs to be override-able.

**Comment by schmidtk** [comment]
Our koop provider has an implementation of `/applyEdits`, but it currently does not work with Esri clients because we can't set the field editable flag. It would be nice if FeatureServer allowed the flag to be set from `metadata.fields`. This was the behavior prior to the fields refactor, but is no longer supported.

**Comment by rgwozdz** [comment]
ok, understood.  We'll get you a patch.

**Comment by schmidtk** [comment]
Thank you, very much appreciated!

**Comment by rgwozdz** [comment]
Fixed by PR https://github.com/koopjs/FeatureServer/pull/248 and released in 4.1.1.
