### ISSUE TITLE
Support Pagination Applied

### ISSUE THREAD

**Issue by dmfenton** [koopjs/FeatureServer#44]
@rgrzywinski

**Comment by mbrownkinetica** [comment]
I ran into the same problem today, where we had already applied the offset in the initial database query and needed a way to skip the slicing imposed in the finishQuery function. I have submitted a PR with a fix, let me know if it needs any tweaking in order to be applied to master. Thanks!

**Comment by dmfenton** [comment]
Done in 78d4fab021473b989022285b1f9999523c66441f
