### ISSUE TITLE
Can't Elect to Skip Winnow Query

### ISSUE THREAD

**Issue by mbrownkinetica** [koopjs/FeatureServer#55]
Would it be possible to add a new property to the filtersApplied object that would optionally skip the Winnow query all together?

Maybe something like (open to suggestions):
```filtersApplied.skipWinnowQuery```

**Background**
I'm currently using Koop as a pass-through provider where we are doing all of the filtering, offset, and limiting directly in the database call. I marked the filtersApplied.where and filtersApplied.geometry to true, but I received an error like this: 

```OFFSET >= features length: [object Object]```

After some digging, I deduced that Winnow was trying to execute an additional query against my dataset, which we don't need for our application of Koop. Adding an optional parameter that allows the user to skip that query would be a huge help.

I am happy to provide the PR if requested. Thanks!

**Update**
I think there is more to this issue than I previously thought. I am going to close it for now until I can dig a little deeper.

**Comment by dmfenton** [comment]
you can set `metadata.filtersApplied = { where: true, offset: true, geometry: true }` and winnow won't filter

**Comment by mbrownkinetica** [comment]
Thanks Daniel! Yeah after a little more digging I came to the same conclusion. Sorry for the hasty posting, I didn't catch that in the docs on the first go-round.
