### ISSUE TITLE
`exceededTransferLimit` is always false

### ISSUE THREAD

**Issue by zbeat** [koopjs/FeatureServer#62]
Related to https://github.com/koopjs/FeatureServer/pull/53/...

We have a pass-through Koop provider, with a `maxRecordCount` of 1000.

Unfortunately the Koop Feature Service is always showing `exceededTransferLimit` as **false**, even when the SCF API returns a total record count of 26,810 (e.g.).  I've verified (via console logging) that `geojson.metadata.limitExceeded` is correcting being set to **true** inside our Koop provider.

Has anyone else had any problems like this?

**Comment by zbeat** [comment]
@dmfenton Any thoughts or suggestions? Sorry to bug you.

**Comment by dmfenton** [comment]
They Zach, this is the relevant code:

https://github.com/koopjs/FeatureServer/blob/master/src/templates.js#L71

metadata.limitExceeded must be true and req.query.limit (default 2000) must be greater than or equal to metadata.maxRecordCount (default 2000)

can you confirm this is the case?

**Comment by dmfenton** [comment]
Let's get on a screen share tomorrow and debug this together.

**Comment by zbeat** [comment]
Fixed in PR #79, released as [2.10.0](https://github.com/koopjs/featureserver/compare/v2.9.3...v2.10.0). Thx @dmfenton! 🎉
