### ISSUE TITLE
Allow providers to control the renderers

### ISSUE THREAD

**Issue by jkerr5** [koopjs/FeatureServer#65]
Allow providers to override the renderer templates by providing renderer metadata of some sort.

**Comment by dmfenton** [comment]
Can you provide a little more detail here? What pieces do you want to override?

**Comment by jkerr5** [comment]
I guess everything, really. For example, right now there's a template for points [here](https://github.com/koopjs/FeatureServer/blob/master/templates/renderers/symbology/point.json). If I want to change it so some features are red points and some are green, I need some way for the provider to communicate that to Koop.

**Comment by dmfenton** [comment]
ok, I have to think about how to best work this in, in the context of a provider. any suggestions?

**Comment by hparkertt** [comment]
@jkerr5 @rgwozdz @ButchGis I think this issue can be closed thanks to #162 ?

**Comment by jkerr5** [comment]
Yes, I believe so. Thanks.
