### ISSUE TITLE
Koop for secure Feature Services

### ISSUE THREAD

**Issue by zbeat** [koopjs/FeatureServer#81]
I'm wondering if anyone used Koop as a secure Feature Service.  For example, has anyone tried implementing [ArcGIS Server Token Authentication](http://enterprise.arcgis.com/en/server/latest/administer/linux/about-arcgis-tokens.htm) or OAuth with Koop?  The former might is probably more simple, but the latter more ideal.

**Comment by dmfenton** [comment]
Auth patterns are on our roadmap. We're looking at [Federation](http://enterprise.arcgis.com/en/portal/latest/administer/linux/federate-an-arcgis-server-site-with-your-portal.htm) first, so that you can control access to a given Koop'd service through a Portal.

**Comment by rgwozdz** [comment]
Happy to announce secure feature services in Koop.  We've developed a new [Authorization plugin-type](https://koopjs.github.io/docs/authorizations/) and released an [initial auth-plugin](https://github.com/koopjs/koop-auth-direct-file) that allows Koop to deliver secured services to AGOL with a file-based identity-store.
