### ISSUE TITLE
Time enabled layer

### ISSUE THREAD

**Issue by keithfraley** [koopjs/FeatureServer#90]
i am curious how to set up the feature service output to be time enabled (and z value for that matter) so that we can use the time sliders in portal for arcgis or agol.

I have hacked together a provider that does this but would much rather this be part of the core product.

**Comment by rgwozdz** [comment]
cross-posted from:  https://github.com/koopjs/koop/issues/305

@keithfraley - Looking at the code, I think the functionality it already there. FeatureServer looks in your provider's metadata to see if you have defined a timeInfo property, and if so, uses that in the layer info service (https://github.com/koopjs/FeatureServer/blob/master/src/templates.js#L54). So try including the timeInfo in your metadata with the following spec:

"timeInfo" : {
     "startTimeField" : "<startTimeFieldName>",
     "endTimeField" : "<endTimeFieldName>",
     "trackIdField" : "<trackIdFieldName>",
     "timeExtent" : [<startTime>, <endTime>],
     "timeReference" : {
       "timeZone" : "<timeZone>",
       "respectsDaylightSaving" : <true | false>
     },
     "timeInterval" : <timeInterval>,
     "timeIntervalUnits" : "<timeIntervalUnits>"
}
Spec pulled from here: https://developers.arcgis.com/rest/services-reference/layer-feature-service-.htm

Will setting up the above `timeInfo` object in provider metadata meet your needs?

**Comment by keithfraley** [comment]
I am unable to find the providers metadata in order to define a timeInfo property.  Can you help me specifcally where this is supposed to go?

**Comment by rgwozdz** [comment]
Guessing you are using Elastic Search provider, so it would go here: https://github.com/koopjs/koop-provider-elasticsearch/blob/master/provider/models/esmodel.js#L22-L24

**Comment by keithfraley** [comment]
brilliant, that is what i was looking for

**Comment by rgwozdz** [comment]
@keithfraley - is this resolved now?

**Comment by keithfraley** [comment]
I will test tonight

**Comment by keithfraley** [comment]
worked great
