### ISSUE TITLE
Why are string field lengths set to 128?

### ISSUE THREAD

**Issue by jkerr5** [koopjs/FeatureServer#93]
A recent change set the length property of string fields to 128. Why was that done? Is 128 characters the maximum length of a string field? I do not see that documented anywhere.

**Comment by rgwozdz** [comment]
@jkerr5 - there was a [commit](https://github.com/koopjs/FeatureServer/commit/be8096978e98a2825c095b0609183641cf3f0e56) that refactored a line where string lengths were set to 128 for the `fields` objects of the layer info service and the query service.  Prior to this, they were also set to 128.  There may be a limit to strings, but its greater than 128 (I've seen lengths of 1000).  Perhaps we could explore a way to set these lengths dynamically.

**Comment by jkerr5** [comment]
OK, maybe I just never noticed it set before. It could be one reason ArcGIS crashes when using our service that has strings longer than 128 characters. If that property must be set, can we allow the provider to specify the field length in the metadata and then koop will only set it to 128 if the provider doesn't provide it?

Right now my provider returns fields like this
```
{ name: 'name', type: 'String' }
```
Can we pass something like this
```
{ name: 'name', type: 'String' , length: 500 }
```
and have koop pass that length through to the field metadata in the layer response?

**Comment by rgwozdz** [comment]
@jkerr5 - it could possible be stored in provider metadata and then transferred to FeatureServer at request time.  What does your `getData` function look like?

**Comment by rgwozdz** [comment]
@jkerr5  - putting together a PR to address this using the solution you mentioned, i.e., passing something like `{ name: 'name', type: 'String' , length: 500 }`.

**Comment by rgwozdz** [comment]
@jkerr5 FeatureServer 2.12.0 now allows you to set a field's length in provider's metadata.
